// Start by creating a variables `numberOfStudents` and `numberOfMentors`
// var age = 27;
// console.log(age);
// var product = 40 * 2;
// console.log(product);
// var diff = 40 - 8;
// console.log(diff);
// var mentors = 34;
// var students = 24;
// var total = 34 + 24;
// var quotient = 40 / 4;
// console.log(quotient);
// console.log(total);
var numOfStudents = 18;
var numberOfMentors = 8;
var total = numOfStudents + numberOfMentors;
var diff = numOfStudents - numberOfMentors;
var quotient = numberOfMentors / 2;
var product = numOfStudents * 4;
console.log(total);
console.log(diff);
console.log(quotient);
console.log(product);
