var name="Daniel   ";
var msg1="My name is ";
var msg2=" and my name is ";
var msg3=" characters long";
var namelength=name.length;
var message=msg1+name+msg2+namelength+msg3;
console.log(message);
name=name.trim();
var namelength=name.length;
var message=msg1+name+msg2+namelength+msg3;
console.log(message);
