var txt = " every one hello";
var res = txt.split("");
var txt = txt.toLowerCase();
var n = txt.replace("hello", "welcome");
var x = txt.substring(12, 16);
var o = txt.indexOf("hello");
var h = txt.search("hello");
var txtType = typeof txt;
console.log(res);
console.log(txt);
console.log(n);
console.log(x);
console.log(o);
console.log(h);
console.log(txtType);
